import re

replacements = {
    "jugador: 'Messi'": "jugador: 'Lionel Messi'",
    "jugador: 'Mbappé'": "jugador: 'Kylian Mbappé'",
    "jugador: 'Mbapppe'": "jugador: 'Kylian Mbappé'",
    "jugador: 'Mbappe'": "jugador: 'Kylian Mbappé'",
    "jugador: 'Ronaldo'": "jugador: 'Cristiano Ronaldo'",
    "jugador: 'Müller'": "jugador: 'Thomas Müller'",
    "jugador: 'Muller'": "jugador: 'Thomas Müller'",
    "jugador: 'Mueller'": "jugador: 'Thomas Müller'",
    "jugador: 'Lewandowski'": "jugador: 'Robert Lewandowski'",
    "jugador: 'Haaland'": "jugador: 'Erling Haaland'",
    "jugador: 'Benzema'": "jugador: 'Karim Benzema'",
    "jugador: 'Modric'": "jugador: 'Luka Modrić'",
    "jugador: 'Modrić'": "jugador: 'Luka Modrić'",
    "jugador: 'Vinicius'": "jugador: 'Vinícius Jr'",
    "jugador: 'Salah'": "jugador: 'Mohamed Salah'",
    "jugador: 'Kane'": "jugador: 'Harry Kane'",
    "jugador: 'Griezmann'": "jugador: 'Antoine Griezmann'",
    "jugador: 'Bellingham'": "jugador: 'Jude Bellingham'",
    "jugador: 'Ramos'": "jugador: 'Sergio Ramos'",
    "jugador: 'Neymar'": "jugador: 'Neymar Jr'",
    "jugador: 'Suárez'": "jugador: 'Luis Suárez'",
    "jugador: 'Suarez'": "jugador: 'Luis Suárez'",
    "jugador: 'Iniesta'": "jugador: 'Andrés Iniesta'",
    "jugador: 'Xavi'": "jugador: 'Xavi Hernández'",
    "jugador: 'Alonso'": "jugador: 'Xabi Alonso'",
    "jugador: 'Torres'": "jugador: 'Fernando Torres'",
    "jugador: 'Villa'": "jugador: 'David Villa'",
    "jugador: 'Silva'": "jugador: 'David Silva'",
    "jugador: 'Pedro'": "jugador: 'Pedro Rodríguez'",
    "jugador: 'Morata'": "jugador: 'Álvaro Morata'",
    "jugador: 'Busquets'": "jugador: 'Sergio Busquets'",
    "jugador: 'Puyol'": "jugador: 'Carles Puyol'",
    "jugador: 'Piqué'": "jugador: 'Gerard Piqué'",
    "jugador: 'Alba'": "jugador: 'Jordi Alba'",
    "jugador: 'Coutinho'": "jugador: 'Philippe Coutinho'",
    "jugador: 'Dembélé'": "jugador: 'Ousmane Dembélé'",
    "jugador: 'Insigne'": "jugador: 'Lorenzo Insigne'",
    "jugador: 'Mertens'": "jugador: 'Dries Mertens'",
    "jugador: 'Osimhen'": "jugador: 'Victor Osimhen'",
    "jugador: 'Higuaín'": "jugador: 'Gonzalo Higuaín'",
    "jugador: 'Higuain'": "jugador: 'Gonzalo Higuaín'",
    "jugador: 'Dybala'": "jugador: 'Paulo Dybala'",
    "jugador: 'Bonucci'": "jugador: 'Leonardo Bonucci'",
    "jugador: 'Chiellini'": "jugador: 'Giorgio Chiellini'",
    "jugador: 'Immobile'": "jugador: 'Ciro Immobile'",
    "jugador: 'Pirlo'": "jugador: 'Andrea Pirlo'",
    "jugador: 'Barella'": "jugador: 'Nicolò Barella'",
    "jugador: 'Lautaro'": "jugador: 'Lautaro Martínez'",
    "jugador: 'Dzeko'": "jugador: 'Edin Džeko'",
    "jugador: 'Lukaku'": "jugador: 'Romelu Lukaku'",
    "jugador: 'Hazard'": "jugador: 'Eden Hazard'",
    "jugador: 'Drogba'": "jugador: 'Didier Drogba'",
    "jugador: 'Lampard'": "jugador: 'Frank Lampard'",
    "jugador: 'Gerrard'": "jugador: 'Steven Gerrard'",
    "jugador: 'Rooney'": "jugador: 'Wayne Rooney'",
    "jugador: 'Pogba'": "jugador: 'Paul Pogba'",
    "jugador: 'Sterling'": "jugador: 'Raheem Sterling'",
    "jugador: 'Sané'": "jugador: 'Leroy Sané'",
    "jugador: 'Foden'": "jugador: 'Phil Foden'",
    "jugador: 'Mahrez'": "jugador: 'Riyad Mahrez'",
    "jugador: 'Agüero'": "jugador: 'Sergio Agüero'",
    "jugador: 'Aguero'": "jugador: 'Sergio Agüero'",
    "jugador: 'Mané'": "jugador: 'Sadio Mané'",
    "jugador: 'Firmino'": "jugador: 'Roberto Firmino'",
    "jugador: 'Jota'": "jugador: 'Diogo Jota'",
    "jugador: 'Gakpo'": "jugador: 'Cody Gakpo'",
    "jugador: 'Son'": "jugador: 'Heung-min Son'",
    "jugador: 'Vardy'": "jugador: 'Jamie Vardy'",
    "jugador: 'Saka'": "jugador: 'Bukayo Saka'",
    "jugador: 'Rashford'": "jugador: 'Marcus Rashford'",
    "jugador: 'Robben'": "jugador: 'Arjen Robben'",
    "jugador: 'Ribéry'": "jugador: 'Franck Ribéry'",
    "jugador: 'Ribery'": "jugador: 'Franck Ribéry'",
    "jugador: 'Klose'": "jugador: 'Miroslav Klose'",
    "jugador: 'Podolski'": "jugador: 'Lukas Podolski'",
    "jugador: 'Kimmich'": "jugador: 'Joshua Kimmich'",
    "jugador: 'Gnabry'": "jugador: 'Serge Gnabry'",
    "jugador: 'Alaba'": "jugador: 'David Alaba'",
    "jugador: 'Kroos'": "jugador: 'Toni Kroos'",
    "jugador: 'Zidane'": "jugador: 'Zinedine Zidane'",
    "jugador: 'Maradona'": "jugador: 'Diego Maradona'",
    "jugador: 'Cavani'": "jugador: 'Edinson Cavani'",
    "jugador: 'Forlán'": "jugador: 'Diego Forlán'",
    "jugador: 'Forlan'": "jugador: 'Diego Forlán'",
    "jugador: 'Tevez'": "jugador: 'Carlos Tevez'",
    "jugador: 'Ibrahimović'": "jugador: 'Zlatan Ibrahimović'",
    "jugador: 'Ibrahimovic'": "jugador: 'Zlatan Ibrahimović'",
    "jugador: 'Valverde'": "jugador: 'Federico Valverde'",
    "jugador: 'Carvajal'": "jugador: 'Dani Carvajal'",
    "jugador: 'Asensio'": "jugador: 'Marco Asensio'",
    "jugador: 'Marcelo'": "jugador: 'Marcelo'",
    "jugador: 'Bale'": "jugador: 'Gareth Bale'",
    "jugador: 'Godín'": "jugador: 'Diego Godín'",
    "jugador: 'Carrasco'": "jugador: 'Yannick Carrasco'",
    "jugador: 'Khedira'": "jugador: 'Sami Khedira'",
    "jugador: 'Özil'": "jugador: 'Mesut Özil'",
    "jugador: 'Schürrle'": "jugador: 'André Schürrle'",
    "jugador: 'Mandžukić'": "jugador: 'Mario Mandžukić'",
    "jugador: 'Mandzukic'": "jugador: 'Mario Mandžukić'",
    "jugador: 'Rakitić'": "jugador: 'Ivan Rakitić'",
    "jugador: 'Yamal'": "jugador: 'Lamine Yamal'",
    "jugador: 'Olmo'": "jugador: 'Dani Olmo'",
    "jugador: 'Oyarzabal'": "jugador: 'Mikel Oyarzabal'",
    "jugador: 'Musiala'": "jugador: 'Jamal Musiala'",
    "jugador: 'Wirtz'": "jugador: 'Florian Wirtz'",
    "jugador: 'Havertz'": "jugador: 'Kai Havertz'",
    "jugador: 'Reus'": "jugador: 'Marco Reus'",
    "jugador: 'Sancho'": "jugador: 'Jadon Sancho'",
    "jugador: 'Pulisic'": "jugador: 'Christian Pulisic'",
    "jugador: 'Goretzka'": "jugador: 'Leon Goretzka'",
    "jugador: 'Thiago'": "jugador: 'Thiago Alcántara'",
    "jugador: 'Vidal'": "jugador: 'Arturo Vidal'",
    "jugador: 'Perisic'": "jugador: 'Ivan Perišić'",
    "jugador: 'Hamsik'": "jugador: 'Marek Hamšík'",
    "jugador: 'Fabian Ruiz'": "jugador: 'Fabián Ruiz'",
    "jugador: 'Milner'": "jugador: 'James Milner'",
    "jugador: 'Henderson'": "jugador: 'Jordan Henderson'",
    "jugador: 'Wijnaldum'": "jugador: 'Georginio Wijnaldum'",
    "jugador: 'Origi'": "jugador: 'Divock Origi'",
    "jugador: 'Maldini'": "jugador: 'Paolo Maldini'",
    "jugador: 'Crespo'": "jugador: 'Hernán Crespo'",
    "jugador: 'Smicer'": "jugador: 'Vladimír Šmicer'",
    "jugador: 'Basler'": "jugador: 'Mario Basler'",
    "jugador: 'Sheringham'": "jugador: 'Teddy Sheringham'",
    "jugador: 'Solskjaer'": "jugador: 'Ole Gunnar Solskjær'",
    "jugador: 'Ballack'": "jugador: 'Michael Ballack'",
    "jugador: 'Inzaghi'": "jugador: 'Filippo Inzaghi'",
    "jugador: 'Totti'": "jugador: 'Francesco Totti'",
    "jugador: 'Del Piero'": "jugador: 'Alessandro Del Piero'",
    "jugador: 'Shevchenko'": "jugador: 'Andriy Shevchenko'",
    "jugador: 'Sneijder'": "jugador: 'Wesley Sneijder'",
    "jugador: 'Robinho'": "jugador: 'Robinho'",
    "jugador: 'Oscar'": "jugador: 'Oscar'",
    "jugador: 'Nainggolan'": "jugador: 'Radja Nainggolan'",
    "jugador: 'Scholes'": "jugador: 'Paul Scholes'",
    "jugador: 'Giggs'": "jugador: 'Ryan Giggs'",
    "jugador: 'Henry'": "jugador: 'Thierry Henry'",
    "jugador: 'Pirès'": "jugador: 'Robert Pirès'",
    "jugador: 'Pires'": "jugador: 'Robert Pirès'",
    "jugador: 'Bergkamp'": "jugador: 'Dennis Bergkamp'",
    "jugador: 'Ljungberg'": "jugador: 'Freddie Ljungberg'",
    "jugador: 'Fabregas'": "jugador: 'Cesc Fàbregas'",
    "jugador: 'Ramsey'": "jugador: 'Aaron Ramsey'",
    "jugador: 'Walcott'": "jugador: 'Theo Walcott'",
    "jugador: 'Giroud'": "jugador: 'Olivier Giroud'",
    "jugador: 'Lacazette'": "jugador: 'Alexandre Lacazette'",
    "jugador: 'Ozil'": "jugador: 'Mesut Özil'",
    "jugador: 'Rice'": "jugador: 'Declan Rice'",
    "jugador: 'Trossard'": "jugador: 'Leandro Trossard'",
    "jugador: 'Martinelli'": "jugador: 'Gabriel Martinelli'",
    "jugador: 'Odegaard'": "jugador: 'Martin Ødegaard'",
    "jugador: 'Matuidi'": "jugador: 'Blaise Matuidi'",
    "jugador: 'Payet'": "jugador: 'Dimitri Payet'",
    "jugador: 'Grealish'": "jugador: 'Jack Grealish'",
    "jugador: 'Cancelo'": "jugador: 'João Cancelo'",
    "jugador: 'Laporte'": "jugador: 'Aymeric Laporte'",
    "jugador: 'Dumfries'": "jugador: 'Denzel Dumfries'",
    "jugador: 'Depay'": "jugador: 'Memphis Depay'",
    "jugador: 'Blind'": "jugador: 'Daley Blind'",
    "jugador: 'Hummels'": "jugador: 'Mats Hummels'",
    "jugador: 'Boateng'": "jugador: 'Jérôme Boateng'",
    "jugador: 'Draxler'": "jugador: 'Julian Draxler'",
    "jugador: 'Götze'": "jugador: 'Mario Götze'",
    "jugador: 'Gotze'": "jugador: 'Mario Götze'",
    "jugador: 'Werner'": "jugador: 'Timo Werner'",
    "jugador: 'Havertz'": "jugador: 'Kai Havertz'",
    "jugador: 'Neuer'": "jugador: 'Manuel Neuer'",
    "jugador: 'Ter Stegen'": "jugador: 'Marc-André ter Stegen'",
    "jugador: 'Mkhitaryan'": "jugador: 'Henrikh Mkhitaryan'",
    "jugador: 'Verratti'": "jugador: 'Marco Verratti'",
    "jugador: 'Rabiot'": "jugador: 'Adrien Rabiot'",
    "jugador: 'Draxler'": "jugador: 'Julian Draxler'",
    "jugador: 'Coman'": "jugador: 'Kingsley Coman'",
    "jugador: 'Gosens'": "jugador: 'Robin Gosens'",
    "jugador: 'Vlahović'": "jugador: 'Dušan Vlahović'",
    "jugador: 'Thuram'": "jugador: 'Marcus Thuram'",
    "jugador: 'Politano'": "jugador: 'Matteo Politano'",
    "jugador: 'Kvaratskhelia'": "jugador: 'Khvicha Kvaratskhelia'",
    "jugador: 'Leão'": "jugador: 'Rafael Leão'",
    "jugador: 'Leao'": "jugador: 'Rafael Leão'",
    "jugador: 'Keita'": "jugador: 'Naby Keita'",
    "jugador: 'Richarlison'": "jugador: 'Richarlison'",
    "jugador: 'Raphinha'": "jugador: 'Raphinha'",
    "jugador: 'Vázquez'": "jugador: 'Lucas Vázquez'",
    "jugador: 'Vazquez'": "jugador: 'Lucas Vázquez'",
    "jugador: 'Casemiro'": "jugador: 'Casemiro'",
    "jugador: 'Militão'": "jugador: 'Éder Militão'",
    "jugador: 'Nacho'": "jugador: 'Nacho Fernández'",
    "jugador: 'Isco'": "jugador: 'Isco'",
    "jugador: 'Kovačić'": "jugador: 'Mateo Kovačić'",
    "jugador: 'Modric'": "jugador: 'Luka Modrić'",
    "jugador: 'Rebić'": "jugador: 'Ante Rebić'",
    "jugador: 'Pašalić'": "jugador: 'Mario Pašalić'",
    "jugador: 'Fletcher'": "jugador: 'Darren Fletcher'",
    "jugador: 'Park'": "jugador: 'Park Ji-sung'",
    "jugador: 'Berbatov'": "jugador: 'Dimitar Berbatov'",
    "jugador: 'Götze'": "jugador: 'Mario Götze'",
    "jugador: 'Ayew'": "jugador: 'André Ayew'",
    "jugador: 'Vittek'": "jugador: 'Robert Vittek'",
    "jugador: 'Quagliarella'": "jugador: 'Fabio Quagliarella'",
    "jugador: 'Grosso'": "jugador: 'Fabio Grosso'",
    "jugador: 'Materazzi'": "jugador: 'Marco Materazzi'",
    "jugador: 'Petit'": "jugador: 'Emmanuel Petit'",
    "jugador: 'Batistuta'": "jugador: 'Gabriel Batistuta'",
    "jugador: 'Vieri'": "jugador: 'Christian Vieri'",
    "jugador: 'Haraguchi'": "jugador: 'Genki Haraguchi'",
    "jugador: 'Fellaini'": "jugador: 'Marouane Fellaini'",
    "jugador: 'Vertonghen'": "jugador: 'Jan Vertonghen'",
    "jugador: 'Chadli'": "jugador: 'Nacer Chadli'",
    "jugador: 'Batshuayi'": "jugador: 'Michy Batshuayi'",
    "jugador: 'Meunier'": "jugador: 'Thomas Meunier'",
    "jugador: 'De Bruyne'": "jugador: 'Kevin De Bruyne'",
    "jugador: 'Navas'": "jugador: 'Keylor Navas'",
    "jugador: 'Pavón'": "jugador: 'Cristian Pavón'",
    "jugador: 'Mercado'": "jugador: 'Gabriel Mercado'",
    "jugador: 'Álvarez'": "jugador: 'Julián Álvarez'",
    "jugador: 'Alvarez'": "jugador: 'Julián Álvarez'",
    "jugador: 'Otamendi'": "jugador: 'Nicolás Otamendi'",
    "jugador: 'Di María'": "jugador: 'Ángel Di María'",
    "jugador: 'Iniesta'": "jugador: 'Andrés Iniesta'",
    "jugador: 'Shaw'": "jugador: 'Luke Shaw'",
    "jugador: 'Palmer'": "jugador: 'Cole Palmer'",
    "jugador: 'Saka'": "jugador: 'Bukayo Saka'",
    "jugador: 'Bellingham'": "jugador: 'Jude Bellingham'",
    "jugador: 'Rashford'": "jugador: 'Marcus Rashford'",
    "jugador: 'Grealish'": "jugador: 'Jack Grealish'",
    "jugador: 'Doan'": "jugador: 'Ritsu Doan'",
    "jugador: 'Asano'": "jugador: 'Takuma Asano'",
    "jugador: 'Gündogan'": "jugador: 'İlkay Gündoğan'",
    "jugador: 'Christensen'": "jugador: 'Andreas Christensen'",
    "jugador: 'Damsgaard'": "jugador: 'Mikkel Damsgaard'",
    "jugador: 'Eriksen'": "jugador: 'Christian Eriksen'",
    "jugador: 'Kjær'": "jugador: 'Simon Kjær'",
    "jugador: 'Cahill'": "jugador: 'Tim Cahill'",
    "jugador: 'Aloisi'": "jugador: 'John Aloisi'",
    "jugador: 'Nakata'": "jugador: 'Hidetoshi Nakata'",
    "jugador: 'Batistuta'": "jugador: 'Gabriel Batistuta'",
    "jugador: 'Salas'": "jugador: 'Marcelo Salas'",
    "jugador: 'En-Nesyri'": "jugador: 'Youssef En-Nesyri'",
    "jugador: 'Pepe'": "jugador: 'Pepe'",
    "jugador: 'Gonçalo Ramos'": "jugador: 'Gonçalo Ramos'",
    "jugador: 'Akanji'": "jugador: 'Manuel Akanji'",
    "jugador: 'Zakaria'": "jugador: 'Denis Zakaria'",
    "jugador: 'Freuler'": "jugador: 'Remo Freuler'",
    "jugador: 'Gavranovic'": "jugador: 'Mario Gavranovic'",
    "jugador: 'Seferović'": "jugador: 'Haris Seferović'",
    "jugador: 'Stancu'": "jugador: 'Bogdan Stancu'",
    "jugador: 'Wober'": "jugador: 'Maximilian Wöber'",
    "jugador: 'Schranz'": "jugador: 'Ivan Schranz'",
    "jugador: 'Akturkoglu'": "jugador: 'Baris Alper Yilmaz'",
    "jugador: 'Demiral'": "jugador: 'Merih Demiral'",
    "jugador: 'Bakasetas'": "jugador: 'Anastasios Bakasetas'",
    "jugador: 'Yuksek'": "jugador: 'Okay Yokuşlu'",
    "jugador: 'Mikautadze'": "jugador: 'Georges Mikautadze'",
    "jugador: 'Mkhitaryan'": "jugador: 'Henrikh Mkhitaryan'",
    "jugador: 'Szymanski'": "jugador: 'Sebastian Szymanski'",
    "jugador: 'Duda'": "jugador: 'Ondrej Duda'",
    "jugador: 'Šporar'": "jugador: 'Andraž Šporar'",
    "jugador: 'Pessina'": "jugador: 'Matteo Pessina'",
    "jugador: 'Chiesa'": "jugador: 'Federico Chiesa'",
    "jugador: 'Bastoni'": "jugador: 'Alessandro Bastoni'",
    "jugador: 'Raspadori'": "jugador: 'Giacomo Raspadori'",
    "jugador: 'Pellè'": "jugador: 'Graziano Pellè'",
    "jugador: 'Berardi'": "jugador: 'Domenico Berardi'",
    "jugador: 'Joselu'": "jugador: 'Joselu'",
    "jugador: 'Yamal'": "jugador: 'Lamine Yamal'",
    "jugador: 'Fabián Ruiz'": "jugador: 'Fabián Ruiz'",
    "jugador: 'Nico Williams'": "jugador: 'Nico Williams'",
    "jugador: 'Mikel Merino'": "jugador: 'Mikel Merino'",
    "jugador: 'Dani Olmo'": "jugador: 'Dani Olmo'",
    "jugador: 'Carvajal'": "jugador: 'Dani Carvajal'",
    "jugador: 'Gavi'": "jugador: 'Gavi'",
    "jugador: 'Pedri'": "jugador: 'Pedri'",
    "jugador: 'Rodrigo'": "jugador: 'Rodri'",
    "jugador: 'Ceballos'": "jugador: 'Dani Ceballos'",
    "jugador: 'Sarabia'": "jugador: 'Pablo Sarabia'",
    "jugador: 'Laporte'": "jugador: 'Aymeric Laporte'",
    "jugador: 'Moura'": "jugador: 'Lucas Moura'",
    "jugador: 'Richarlison'": "jugador: 'Richarlison'",
    "jugador: 'Rodrigo de Paul'": "jugador: 'Rodrigo De Paul'",
    "jugador: 'Tielemans'": "jugador: 'Youri Tielemans'",
    "jugador: 'Maddison'": "jugador: 'James Maddison'",
    "jugador: 'Iheanacho'": "jugador: 'Kelechi Iheanacho'",
    "jugador: 'Albrighton'": "jugador: 'Marc Albrighton'",
    "jugador: 'Doku'": "jugador: 'Jérémy Doku'",
    "jugador: 'Isak'": "jugador: 'Alexander Isak'",
    "jugador: 'Trippier'": "jugador: 'Kieran Trippier'",
    "jugador: 'Rodrygo'": "jugador: 'Rodrygo Goes'",
    "jugador: 'Vinicius'": "jugador: 'Vinícius Jr'",
    "jugador: 'Militão'": "jugador: 'Éder Militão'",
    "jugador: 'Hakimi'": "jugador: 'Achraf Hakimi'",
    "jugador: 'Vitinha'": "jugador: 'Vitinha'",
    "jugador: 'Kolo Muani'": "jugador: 'Randal Kolo Muani'",
    "jugador: 'Mbappe'": "jugador: 'Kylian Mbappé'",
    "jugador: 'Dembele'": "jugador: 'Ousmane Dembélé'",
    "jugador: 'Kulusevski'": "jugador: 'Dejan Kulusevski'",
    "jugador: 'Bentancur'": "jugador: 'Rodrigo Bentancur'",
    "jugador: 'Bergvall'": "jugador: 'Lucas Bergvall'",
    "jugador: 'Mudryk'": "jugador: 'Mykhailo Mudryk'",
    "jugador: 'Jackson'": "jugador: 'Nicolas Jackson'",
    "jugador: 'Guimaraes'": "jugador: 'Bruno Guimarães'",
    "jugador: 'Barnes'": "jugador: 'Harvey Barnes'",
    "jugador: 'Gundogan'": "jugador: 'İlkay Gündoğan'",
    "jugador: 'Sorloth'": "jugador: 'Alexander Sørloth'",
    "jugador: 'Lino'": "jugador: 'Samuel Lino'",
    "jugador: 'Saúl'": "jugador: 'Saúl Ñíguez'",
    "jugador: 'Saul'": "jugador: 'Saúl Ñíguez'",
    "jugador: 'Correa'": "jugador: 'Joaquín Correa'",
    "jugador: 'Morata'": "jugador: 'Álvaro Morata'",
    "jugador: 'Griezmann'": "jugador: 'Antoine Griezmann'",
    "jugador: 'Depay'": "jugador: 'Memphis Depay'",
    "jugador: 'Marcos Llorente'": "jugador: 'Marcos Llorente'",
    "jugador: 'Aubameyang'": "jugador: 'Pierre-Emerick Aubameyang'",
    "jugador: 'Eto'o'": "jugador: 'Samuel Eto\\'o'",
    "jugador: 'Kluivert'": "jugador: 'Patrick Kluivert'",
    "jugador: 'Raúl'": "jugador: 'Raúl González'",
    "jugador: 'Raul'": "jugador: 'Raúl González'",
    "jugador: 'Figo'": "jugador: 'Luís Figo'",
    "jugador: 'Morientes'": "jugador: 'Fernando Morientes'",
    "jugador: 'McManaman'": "jugador: 'Steve McManaman'",
    "jugador: 'Mijatović'": "jugador: 'Predrag Mijatović'",
    "jugador: 'Ronaldinho'": "jugador: 'Ronaldinho'",
    "jugador: 'Rivaldo'": "jugador: 'Rivaldo'",
    "jugador: 'Romario'": "jugador: 'Romário'",
    "jugador: 'Bebeto'": "jugador: 'Bebeto'",
    "jugador: 'Pelé'": "jugador: 'Pelé'",
    "jugador: 'Pele'": "jugador: 'Pelé'",
    "jugador: 'Jairzinho'": "jugador: 'Jairzinho'",
    "jugador: 'Kempes'": "jugador: 'Mario Kempes'",
    "jugador: 'Burruchaga'": "jugador: 'Jorge Burruchaga'",
    "jugador: 'Brown'": "jugador: 'José Luis Brown'",
    "jugador: 'Valdano'": "jugador: 'Jorge Valdano'",
    "jugador: 'Rummenigge'": "jugador: 'Karl-Heinz Rummenigge'",
    "jugador: 'Völler'": "jugador: 'Rudi Völler'",
    "jugador: 'Neeskens'": "jugador: 'Johan Neeskens'",
    "jugador: 'Breitner'": "jugador: 'Paul Breitner'",
    "jugador: 'Hurst'": "jugador: 'Geoff Hurst'",
    "jugador: 'Peters'": "jugador: 'Martin Peters'",
    "jugador: 'Weber'": "jugador: 'Helmut Haller'",
    "jugador: 'Haller'": "jugador: 'Helmut Haller'",
    "jugador: 'Brehme'": "jugador: 'Andreas Brehme'",
    "jugador: 'Nanninga'": "jugador: 'Dick Nanninga'",
    "jugador: 'Bertoni'": "jugador: 'Daniel Bertoni'",
    "jugador: 'Tardelli'": "jugador: 'Marco Tardelli'",
    "jugador: 'Rossi'": "jugador: 'Paolo Rossi'",
    "jugador: 'Altobelli'": "jugador: 'Alessandro Altobelli'",
    "jugador: 'Liedholm'": "jugador: 'Nils Liedholm'",
    "jugador: 'Simonsson'": "jugador: 'Agne Simonsson'",
    "jugador: 'Vavá'": "jugador: 'Vavá'",
    "jugador: 'Boninsegna'": "jugador: 'Roberto Boninsegna'",
    "jugador: 'Gérson'": "jugador: 'Gérson'",
    "jugador: 'Alberto'": "jugador: 'Carlos Alberto'",
    "jugador: 'Sócrates'": "jugador: 'Sócrates'",
    "jugador: 'Falcão'": "jugador: 'Falcão'",
    "jugador: 'Schillaci'": "jugador: 'Salvatore Schillaci'",
    "jugador: 'Stoichkov'": "jugador: 'Hristo Stoichkov'",
    "jugador: 'Baggio'": "jugador: 'Roberto Baggio'",
    "jugador: 'Lineker'": "jugador: 'Gary Lineker'",
    "jugador: 'Owen'": "jugador: 'Michael Owen'",
    "jugador: 'Heskey'": "jugador: 'Emile Heskey'",
    "jugador: 'Fowler'": "jugador: 'Robbie Fowler'",
    "jugador: 'Crouch'": "jugador: 'Peter Crouch'",
    "jugador: 'Carroll'": "jugador: 'Andy Carroll'",
    "jugador: 'Abraham'": "jugador: 'Tammy Abraham'",
    "jugador: 'Mount'": "jugador: 'Mason Mount'",
    "jugador: 'Azpilicueta'": "jugador: 'César Azpilicueta'",
    "jugador: 'Rudiger'": "jugador: 'Antonio Rüdiger'",
    "jugador: 'Havertz'": "jugador: 'Kai Havertz'",
    "jugador: 'Telles'": "jugador: 'Alex Telles'",
    "jugador: 'Moreno'": "jugador: 'Gerard Moreno'",
    "jugador: 'Parejo'": "jugador: 'Dani Parejo'",
    "jugador: 'Adeyemi'": "jugador: 'Karim Adeyemi'",
    "jugador: 'Guirassy'": "jugador: 'Serhou Guirassy'",
    "jugador: 'Brandt'": "jugador: 'Julian Brandt'",
    "jugador: 'Malen'": "jugador: 'Donyell Malen'",
    "jugador: 'Choupo-Moting'": "jugador: 'Eric Maxim Choupo-Moting'",
    "jugador: 'Davies'": "jugador: 'Alphonso Davies'",
    "jugador: 'Coman'": "jugador: 'Kingsley Coman'",
    "jugador: 'Sané'": "jugador: 'Leroy Sané'",
    "jugador: 'Goretzka'": "jugador: 'Leon Goretzka'",
    "jugador: 'Hofmann'": "jugador: 'Jonas Hofmann'",
    "jugador: 'Tella'": "jugador: 'Nathan Tella'",
    "jugador: 'Mbappé'": "jugador: 'Kylian Mbappé'",
    "jugador: 'Puyal'": "jugador: 'Carles Puyol'",
    "jugador: 'Mingueza'": "jugador: 'Óscar Mingueza'",
    "jugador: 'Ansu Fati'": "jugador: 'Ansu Fati'",
    "jugador: 'Braithwaite'": "jugador: 'Martin Braithwaite'",
    "jugador: 'Dest'": "jugador: 'Sergiño Dest'",
    "jugador: 'Vietto'": "jugador: 'Luciano Vietto'",
    "jugador: 'Ben Yedder'": "jugador: 'Wissam Ben Yedder'",
    "jugador: 'Reyes'": "jugador: 'José Antonio Reyes'",
    "jugador: 'Eder'": "jugador: 'Éder'",
    "jugador: 'Quaresma'": "jugador: 'Ricardo Quaresma'",
    "jugador: 'Blaszczykowski'": "jugador: 'Jakub Błaszczykowski'",
    "jugador: 'Renato Sanches'": "jugador: 'Renato Sanches'",
    "jugador: 'Williams'": "jugador: 'Ashley Williams'",
    "jugador: 'Robson-Kanu'": "jugador: 'Hal Robson-Kanu'",
    "jugador: 'Vokes'": "jugador: 'Sam Vokes'",
    "jugador: 'Hector'": "jugador: 'Jonas Hector'",
    "jugador: 'Draxler'": "jugador: 'Julian Draxler'",
    "jugador: 'Pilar'": "jugador: 'Václav Pilar'",
    "jugador: 'Shirokov'": "jugador: 'Roman Shirokov'",
    "jugador: 'Pavlyuchenko'": "jugador: 'Roman Pavlyuchenko'",
    "jugador: 'Dzagoev'": "jugador: 'Alan Dzagoev'",
    "jugador: 'Krohn-Dehli'": "jugador: 'Mikkel Krohn-Dehli'",
    "jugador: 'Nasri'": "jugador: 'Samir Nasri'",
    "jugador: 'Lescott'": "jugador: 'Joleon Lescott'",
    "jugador: 'Arshavin'": "jugador: 'Andrei Arshavin'",
    "jugador: 'Gusev'": "jugador: 'Rolan Gusev'",
    "jugador: 'Klasnić'": "jugador: 'Ivan Klasnić'",
    "jugador: 'Srna'": "jugador: 'Darijo Srna'",
    "jugador: 'Olić'": "jugador: 'Ivica Olić'",
    "jugador: 'Schweinsteiger'": "jugador: 'Bastian Schweinsteiger'",
    "jugador: 'Lahm'": "jugador: 'Philipp Lahm'",
    "jugador: 'Dempsey'": "jugador: 'Clint Dempsey'",
    "jugador: 'Donovan'": "jugador: 'Landon Donovan'",
    "jugador: 'Chicharito'": "jugador: 'Javier Hernández'",
    "jugador: 'Stindl'": "jugador: 'Lars Stindl'",
    "jugador: 'Rudy'": "jugador: 'Sebastian Rudy'",
    "jugador: 'Kimmich'": "jugador: 'Joshua Kimmich'",
    "jugador: 'Rebrov'": "jugador: 'Serhiy Rebrov'",
    "jugador: 'Kalinichenko'": "jugador: 'Maksym Kalinichenko'",
    "jugador: 'Golovin'": "jugador: 'Aleksandr Golovin'",
    "jugador: 'Gazinsky'": "jugador: 'Yuri Gazinsky'",
    "jugador: 'Cheryshev'": "jugador: 'Denis Cheryshev'",
    "jugador: 'Dzyuba'": "jugador: 'Artem Dzyuba'",
    "jugador: 'Samaras'": "jugador: 'Georgios Samaras'",
    "jugador: 'Karagounis'": "jugador: 'Giorgos Karagounis'",
    "jugador: 'Mesiha'": "jugador: 'Mesut Özil'",
    "jugador: 'Holes'": "jugador: 'Tomáš Holeš'",
    "jugador: 'Schick'": "jugador: 'Patrik Schick'",
    "jugador: 'Pesic'": "jugador: 'Mislav Oršić'",
    "jugador: 'Karnicnik'": "jugador: 'Jure Balkovec'",
    "jugador: 'Fiola'": "jugador: 'Attila Fiola'",
    "jugador: 'Varga'": "jugador: 'Kevin Varga'",
    "jugador: 'Amdouni'": "jugador: 'Zeki Amdouni'",
    "jugador: 'Mitrović'": "jugador: 'Aleksandar Mitrović'",
    "jugador: 'Bajrami'": "jugador: 'Nedim Bajrami'",
    "jugador: 'Dragus'": "jugador: 'Denis Drăguș'",
    "jugador: 'Marin'": "jugador: 'Răzvan Marin'",
    "jugador: 'Pandev'": "jugador: 'Goran Pandev'",
    "jugador: 'Lainer'": "jugador: 'Stefan Lainer'",
    "jugador: 'Kalajdzic'": "jugador: 'Sasa Kalajdzic'",
    "jugador: 'Baumgartner'": "jugador: 'Christoph Baumgartner'",
    "jugador: 'Provod'": "jugador: 'Lukáš Provod'",
    "jugador: 'Conceiçao'": "jugador: 'Francisco Conceição'",
    "jugador: 'Pohjanpalo'": "jugador: 'Joel Pohjanpalo'",
    "jugador: 'Moore'": "jugador: 'Kieffer Moore'",
    "jugador: 'Shankland'": "jugador: 'Lawrence Shankland'",
    "jugador: 'Füllkrug'": "jugador: 'Niclas Füllkrug'",
    "jugador: 'Raspadori'": "jugador: 'Giacomo Raspadori'",
    "jugador: 'Buksa'": "jugador: 'Adam Buksa'",
    "jugador: 'Simons'": "jugador: 'Xavi Simons'",
    "jugador: 'Watkins'": "jugador: 'Ollie Watkins'",
    "jugador: 'Morten'": "jugador: 'Wout Weghorst'",
    "jugador: 'Goodwin'": "jugador: 'Craig Goodwin'",
    "jugador: 'Rabiot'": "jugador: 'Adrien Rabiot'",
    "jugador: 'Giroud'": "jugador: 'Olivier Giroud'",
    "jugador: 'Christensen'": "jugador: 'Andreas Christensen'",
    "jugador: 'Valencia'": "jugador: 'Enner Valencia'",
    "jugador: 'Klaassen'": "jugador: 'Davy Klaassen'",
    "jugador: 'De Jong'": "jugador: 'Frenkie de Jong'",
    "jugador: 'Caicedo'": "jugador: 'Moisés Caicedo'",
    "jugador: 'Diallo'": "jugador: 'Krepin Diallo'",
    "jugador: 'Koulibaly'": "jugador: 'Kalidou Koulibaly'",
    "jugador: 'Weah'": "jugador: 'Timothy Weah'",
    "jugador: 'Salisu'": "jugador: 'Mohammed Salisu'",
    "jugador: 'Kudus'": "jugador: 'Mohammed Kudus'",
    "jugador: 'Bukari'": "jugador: 'Osman Bukari'",
    "jugador: 'Abde'": "jugador: 'Abde Ezzalzouli'",
    "jugador: 'Sabiri'": "jugador: 'Abdelhamid Sabiri'",
    "jugador: 'Al-Dawsari'": "jugador: 'Salem Al-Dawsari'",
    "jugador: 'Al-Shahrani'": "jugador: 'Yasser Al-Shahrani'",
    "jugador: 'Richarlison'": "jugador: 'Richarlison'",
    "jugador: 'Levandowski'": "jugador: 'Robert Lewandowski'",
    "jugador: 'Aboubakar'": "jugador: 'Vincent Aboubakar'",
    "jugador: 'Giménez'": "jugador: 'José María Giménez'",
    "jugador: 'Maxi Gómez'": "jugador: 'Maxi Gómez'",
    "jugador: 'Nunez'": "jugador: 'Darwin Núñez'",
    "jugador: 'Ugarte'": "jugador: 'Manuel Ugarte'",
    "jugador: 'Bentancur'": "jugador: 'Rodrigo Bentancur'",
    "jugador: 'Savinho'": "jugador: 'Savinho'",
    "jugador: 'Díaz'": "jugador: 'Luis Díaz'",
    "jugador: 'Córdoba'": "jugador: 'Jhon Córdoba'",
    "jugador: 'Sinisterra'": "jugador: 'Luis Sinisterra'",
    "jugador: 'MacAllister'": "jugador: 'Alexis Mac Allister'",
    "jugador: 'Meza'": "jugador: 'Maximiliano Meza'",
    "jugador: 'Higuain'": "jugador: 'Gonzalo Higuaín'",
    "jugador: 'Aranguiz'": "jugador: 'Charles Aránguiz'",
    "jugador: 'Vargas'": "jugador: 'Eduardo Vargas'",
    "jugador: 'Dani Olmo'": "jugador: 'Dani Olmo'",
    "jugador: 'Ferran Torres'": "jugador: 'Ferran Torres'",
    "jugador: 'Carlos Soler'": "jugador: 'Carlos Soler'",
    "jugador: 'Marco Asensio'": "jugador: 'Marco Asensio'",
    "jugador: 'Gündogan'": "jugador: 'İlkay Gündoğan'",
    "jugador: 'Guerreiro'": "jugador: 'Raphaël Guerreiro'",
    "jugador: 'Leão'": "jugador: 'Rafael Leão'",
    "jugador: 'João Félix'": "jugador: 'João Félix'",
    "jugador: 'Joao Felix'": "jugador: 'João Félix'",
    "jugador: 'Pepe'": "jugador: 'Pepe'",
    "jugador: 'Neto'": "jugador: 'Pedro Neto'",
    "jugador: 'Otavio'": "jugador: 'Otávio'",
    "jugador: 'Guedes'": "jugador: 'Gonçalo Guedes'",
    "jugador: 'Nani'": "jugador: 'Nani'",
    "jugador: 'Aimar'": "jugador: 'Pablo Aimar'",
    "jugador: 'Baraja'": "jugador: 'Rubén Baraja'",
    "jugador: 'Saviola'": "jugador: 'Javier Saviola'",
    "jugador: 'Rivaldo'": "jugador: 'Rivaldo'",
    "jugador: 'Riquelme'": "jugador: 'Juan Román Riquelme'",
    "jugador: 'Rodrigo'": "jugador: 'Rodrigo Moreno'",
    "jugador: 'Gameiro'": "jugador: 'Kevin Gameiro'",
    "jugador: 'Xhaka'": "jugador: 'Granit Xhaka'",
    "jugador: 'Embolo'": "jugador: 'Breel Embolo'",
    "jugador: 'Zuber'": "jugador: 'Steven Zuber'",
    "jugador: 'Gavranovic'": "jugador: 'Mario Gavranovic'",
    "jugador: 'Sissoko'": "jugador: 'Moussa Sissoko'",
    "jugador: 'Cabaye'": "jugador: 'Yohan Cabaye'",
    "jugador: 'Matuidi'": "jugador: 'Blaise Matuidi'",
    "jugador: 'Martial'": "jugador: 'Anthony Martial'",
    "jugador: 'Thuram'": "jugador: 'Marcus Thuram'",
    "jugador: 'Umtiti'": "jugador: 'Samuel Umtiti'",
    "jugador: 'Varane'": "jugador: 'Raphaël Varane'",
    "jugador: 'Lloris'": "jugador: 'Hugo Lloris'",
    "jugador: 'Lloris'": "jugador: 'Hugo Lloris'",
    "jugador: 'Deschamps'": "jugador: 'Didier Deschamps'",
    "jugador: 'Suker'": "jugador: 'Davor Šuker'",
    "jugador: 'Thuram'": "jugador: 'Lilian Thuram'",
    "jugador: 'Blanc'": "jugador: 'Laurent Blanc'",
    "jugador: 'Wiltord'": "jugador: 'Sylvain Wiltord'",
    "jugador: 'Trezeguet'": "jugador: 'David Trezeguet'",
    "jugador: 'Delvecchio'": "jugador: 'Marco Delvecchio'",
    "jugador: 'Bierhoff'": "jugador: 'Oliver Bierhoff'",
    "jugador: 'Berger'": "jugador: 'Patrik Berger'",
    "jugador: 'Jensen'": "jugador: 'John Jensen'",
    "jugador: 'Vilfort'": "jugador: 'Kim Vilfort'",
    "jugador: 'Charisteas'": "jugador: 'Angelos Charisteas'",
    "jugador: 'Zanetti'": "jugador: 'Javier Zanetti'",
    "jugador: 'Milito'": "jugador: 'Diego Milito'",
    "jugador: 'Sneijder'": "jugador: 'Wesley Sneijder'",
    "jugador: 'Samuel'": "jugador: 'Walter Samuel'",
    "jugador: 'Cambiasso'": "jugador: 'Esteban Cambiasso'",
    "jugador: 'Ayala'": "jugador: 'Roberto Ayala'",
    "jugador: 'Rodríguez'": "jugador: 'Maxi Rodríguez'",
    "jugador: 'Bravo'": "jugador: 'Jorge Bravo'",
    "jugador: 'Zinha'": "jugador: 'Zinha'",
    "jugador: 'Iaquinta'": "jugador: 'Vincenzo Iaquinta'",
    "jugador: 'Zambrotta'": "jugador: 'Gianluca Zambrotta'",
    "jugador: 'Toni'": "jugador: 'Luca Toni'",
    "jugador: 'Grosso'": "jugador: 'Fabio Grosso'",
    "jugador: 'De Rossi'": "jugador: 'Daniele De Rossi'",
    "jugador: 'Gilardino'": "jugador: 'Alberto Gilardino'",
    "jugador: 'Pirlo'": "jugador: 'Andrea Pirlo'",
    "jugador: 'Perrotta'": "jugador: 'Simone Perrotta'",
    "jugador: 'Wanchope'": "jugador: 'Paulo Wanchope'",
    "jugador: 'Klose'": "jugador: 'Miroslav Klose'",
    "jugador: 'Lahm'": "jugador: 'Philipp Lahm'",
    "jugador: 'Frings'": "jugador: 'Torsten Frings'",
    "jugador: 'Schneider'": "jugador: 'Bernd Schneider'",
    "jugador: 'Bode'": "jugador: 'Mike Bode'",
    "jugador: 'Jancker'": "jugador: 'Carsten Jancker'",
    "jugador: 'Ballack'": "jugador: 'Michael Ballack'",
    "jugador: 'Tenorio'": "jugador: 'Carlos Tenorio'",
    "jugador: 'Delgado'": "jugador: 'Agustín Delgado'",
    "jugador: 'Gamarra'": "jugador: 'Carlos Gamarra'",
    "jugador: 'McBride'": "jugador: 'Brian McBride'",
    "jugador: 'Hwang Sun-hong'": "jugador: 'Hwang Sun-hong'",
    "jugador: 'Ahn Jung-hwan'": "jugador: 'Ahn Jung-hwan'",
    "jugador: 'Park Ji-sung'": "jugador: 'Park Ji-sung'",
    "jugador: 'Nakata'": "jugador: 'Hidetoshi Nakata'",
    "jugador: 'Cahill'": "jugador: 'Tim Cahill'",
    "jugador: 'Aloisi'": "jugador: 'John Aloisi'",
    "jugador: 'Batistuta'": "jugador: 'Gabriel Batistuta'",
    "jugador: 'Vieri'": "jugador: 'Christian Vieri'",
    "jugador: 'Jeremies'": "jugador: 'Jens Jeremies'",
    "jugador: 'Kolarov'": "jugador: 'Aleksandar Kolarov'",
    "jugador: 'Zabaleta'": "jugador: 'Pablo Zabaleta'",
    "jugador: 'Džeko'": "jugador: 'Edin Džeko'",
    "jugador: 'Cissé'": "jugador: 'Papiss Cissé'",
    "jugador: 'Mackie'": "jugador: 'Jamie Mackie'",
    "jugador: 'Van Persie'": "jugador: 'Robin van Persie'",
    "jugador: 'Oxlade-Chamberlain'": "jugador: 'Alex Oxlade-Chamberlain'",
    "jugador: 'Götze'": "jugador: 'Mario Götze'",
    "jugador: 'Mkhitaryan'": "jugador: 'Henrikh Mkhitaryan'",
    "jugador: 'Gosens'": "jugador: 'Robin Gosens'",
    "jugador: 'Perisic'": "jugador: 'Ivan Perišić'",
    "jugador: 'Gnabry'": "jugador: 'Serge Gnabry'",
    "jugador: 'Müller'": "jugador: 'Thomas Müller'",
    "jugador: 'Sané'": "jugador: 'Leroy Sané'",
    "jugador: 'Adeyemi'": "jugador: 'Karim Adeyemi'",
    "jugador: 'Guirassy'": "jugador: 'Serhou Guirassy'",
    "jugador: 'Brandt'": "jugador: 'Julian Brandt'",
    "jugador: 'Reus'": "jugador: 'Marco Reus'",
    "jugador: 'Sancho'": "jugador: 'Jadon Sancho'",
    "jugador: 'Haaland'": "jugador: 'Erling Haaland'",
    "jugador: 'Immobile'": "jugador: 'Ciro Immobile'",
    "jugador: 'Insigne'": "jugador: 'Lorenzo Insigne'",
    "jugador: 'Barella'": "jugador: 'Nicolò Barella'",
    "jugador: 'Osimhen'": "jugador: 'Victor Osimhen'",
    "jugador: 'Politano'": "jugador: 'Matteo Politano'",
    "jugador: 'Elmas'": "jugador: 'Eljif Elmas'",
    "jugador: 'Simeone'": "jugador: 'Giovanni Simeone'",
    "jugador: 'Anguissa'": "jugador: 'André-Frank Zambo Anguissa'",
    "jugador: 'Kvaratskhelia'": "jugador: 'Khvicha Kvaratskhelia'",
    "jugador: 'Raspadori'": "jugador: 'Giacomo Raspadori'",
    "jugador: 'Lautaro'": "jugador: 'Lautaro Martínez'",
    "jugador: 'Dzeko'": "jugador: 'Edin Džeko'",
    "jugador: 'Lukaku'": "jugador: 'Romelu Lukaku'",
    "jugador: 'Correa'": "jugador: 'Joaquín Correa'",
    "jugador: 'Acerbi'": "jugador: 'Francesco Acerbi'",
    "jugador: 'Thuram'": "jugador: 'Marcus Thuram'",
    "jugador: 'Leao'": "jugador: 'Rafael Leão'",
    "jugador: 'Leão'": "jugador: 'Rafael Leão'",
    "jugador: 'Vlahović'": "jugador: 'Dušan Vlahović'",
    "jugador: 'Milik'": "jugador: 'Arkadiusz Milik'",
    "jugador: 'Callejón'": "jugador: 'José Callejón'",
    "jugador: 'Callejon'": "jugador: 'José Callejón'",
    "jugador: 'Mertens'": "jugador: 'Dries Mertens'",
    "jugador: 'Veretout'": "jugador: 'Jordan Veretout'",
    "jugador: 'Zaniolo'": "jugador: 'Nicolò Zaniolo'",
    "jugador: 'Nainggolan'": "jugador: 'Radja Nainggolan'",
    "jugador: 'Perotti'": "jugador: 'Diego Perotti'",
    "jugador: 'Pjanic'": "jugador: 'Miralem Pjanić'",
    "jugador: 'Dybala'": "jugador: 'Paulo Dybala'",
    "jugador: 'Mandzukic'": "jugador: 'Mario Mandžukić'",
    "jugador: 'McKennie'": "jugador: 'Weston McKennie'",
    "jugador: 'Hamsik'": "jugador: 'Marek Hamšík'",
    "jugador: 'Marchisio'": "jugador: 'Claudio Marchisio'",
    "jugador: 'Quagliarella'": "jugador: 'Fabio Quagliarella'",
    "jugador: 'Giovinco'": "jugador: 'Sebastian Giovinco'",
    "jugador: 'Matri'": "jugador: 'Alessandro Matri'",
    "jugador: 'Vucinic'": "jugador: 'Mirko Vučinić'",
    "jugador: 'Palacio'": "jugador: 'Rodrigo Palacio'",
    "jugador: 'Candreva'": "jugador: 'Antonio Candreva'",
    "jugador: 'Young'": "jugador: 'Ashley Young'",
    "jugador: 'Vecino'": "jugador: 'Matías Vecino'",
    "jugador: 'Icardi'": "jugador: 'Mauro Icardi'",
    "jugador: 'Vidal'": "jugador: 'Arturo Vidal'",
    "jugador: 'Cambiasso'": "jugador: 'Esteban Cambiasso'",
    "jugador: 'Maicon'": "jugador: 'Maicon'",
    "jugador: 'Milito'": "jugador: 'Diego Milito'",
    "jugador: 'Sneijder'": "jugador: 'Wesley Sneijder'",
    "jugador: 'Ibrahimovic'": "jugador: 'Zlatan Ibrahimović'",
    "jugador: 'Totti'": "jugador: 'Francesco Totti'",
    "jugador: 'Shevchenko'": "jugador: 'Andriy Shevchenko'",
    "jugador: 'Inzaghi'": "jugador: 'Filippo Inzaghi'",
    "jugador: 'Pato'": "jugador: 'Alexandre Pato'",
    "jugador: 'Cavani'": "jugador: 'Edinson Cavani'",
    "jugador: 'Draxler'": "jugador: 'Julian Draxler'",
    "jugador: 'Matuidi'": "jugador: 'Blaise Matuidi'",
    "jugador: 'Lucas'": "jugador: 'Lucas Moura'",
    "jugador: 'Maxwell'": "jugador: 'Maxwell'",
    "jugador: 'Lavezzi'": "jugador: 'Ezequiel Lavezzi'",
    "jugador: 'Marquinhos'": "jugador: 'Marquinhos'",
    "jugador: 'Mkhitaryan'": "jugador: 'Henrikh Mkhitaryan'",
    "jugador: 'Malcom'": "jugador: 'Malcom'",
    "jugador: 'Munir'": "jugador: 'Munir El Haddadi'",
    "jugador: 'Sergi Roberto'": "jugador: 'Sergi Roberto'",
    "jugador: 'Kurzawa'": "jugador: 'Layvin Kurzawa'",
    "jugador: 'Meunier'": "jugador: 'Thomas Meunier'",
    "jugador: 'Milner'": "jugador: 'James Milner'",
    "jugador: 'Hakimi'": "jugador: 'Achraf Hakimi'",
    "jugador: 'Vitinha'": "jugador: 'Vitinha'",
    "jugador: 'Kolo Muani'": "jugador: 'Randal Kolo Muani'",
    "jugador: 'Dembele'": "jugador: 'Ousmane Dembélé'",
    "jugador: 'Doue'": "jugador: 'Désiré Doué'",
    "jugador: 'Ramos'": "jugador: 'Gonçalo Ramos'",
    "jugador: 'Ben Yedder'": "jugador: 'Wissam Ben Yedder'",
    "jugador: 'Golovin'": "jugador: 'Aleksandr Golovin'",
    "jugador: 'Lacazette'": "jugador: 'Alexandre Lacazette'",
    "jugador: 'Fekir'": "jugador: 'Nabil Fekir'",
    "jugador: 'Neymar'": "jugador: 'Neymar Jr'",
    "jugador: 'Richarlison'": "jugador: 'Richarlison'",
    "jugador: 'Gabigol'": "jugador: 'Gabriel Barbosa'",
    "jugador: 'Coutinho'": "jugador: 'Philippe Coutinho'",
    "jugador: 'Firmino'": "jugador: 'Roberto Firmino'",
    "jugador: 'Everton'": "jugador: 'Everton Soares'",
    "jugador: 'Savinho'": "jugador: 'Savinho'",
    "jugador: 'Luis Suárez'": "jugador: 'Luis Suárez'",
    "jugador: 'Luis Díaz'": "jugador: 'Luis Díaz'",
    "jugador: 'Diaz'": "jugador: 'Luis Díaz'",
    "jugador: 'James'": "jugador: 'James Rodríguez'",
    "jugador: 'Bacca'": "jugador: 'Carlos Bacca'",
    "jugador: 'Falcao'": "jugador: 'Radamel Falcao'",
    "jugador: 'Zapata'": "jugador: 'Duván Zapata'",
    "jugador: 'Balotelli'": "jugador: 'Mario Balotelli'",
    "jugador: 'Robben'": "jugador: 'Arjen Robben'",
    "jugador: 'Depay'": "jugador: 'Memphis Depay'",
    "jugador: 'Blind'": "jugador: 'Daley Blind'",
    "jugador: 'Van Nistelrooy'": "jugador: 'Ruud van Nistelrooy'",
    "jugador: 'Ribéry'": "jugador: 'Franck Ribéry'",
    "jugador: 'Robben'": "jugador: 'Arjen Robben'",
    "jugador: 'Coman'": "jugador: 'Kingsley Coman'",
    "jugador: 'Alario'": "jugador: 'Lucas Alario'",
    "jugador: 'Demirbay'": "jugador: 'Kerem Demirbay'",
    "jugador: 'Thiago'": "jugador: 'Thiago Alcántara'",
    "jugador: 'Dante'": "jugador: 'Dante'",
    "jugador: 'Gomez'": "jugador: 'Mario Gómez'",
    "jugador: 'Martínez'": "jugador: 'Javi Martínez'",
    "jugador: 'Lahm'": "jugador: 'Philipp Lahm'",
    "jugador: 'Rafinha'": "jugador: 'Rafinha'",
    "jugador: 'Ribery'": "jugador: 'Franck Ribéry'",
    "jugador: 'Muller'": "jugador: 'Thomas Müller'",
    "jugador: 'Mueller'": "jugador: 'Thomas Müller'",
    "jugador: 'Gotze'": "jugador: 'Mario Götze'",
    "jugador: 'Ramsey'": "jugador: 'Aaron Ramsey'",
    "jugador: 'Walcott'": "jugador: 'Theo Walcott'",
    "jugador: 'Wilshere'": "jugador: 'Jack Wilshere'",
    "jugador: 'Fabregas'": "jugador: 'Cesc Fàbregas'",
    "jugador: 'Welbeck'": "jugador: 'Danny Welbeck'",
    "jugador: 'Podolski'": "jugador: 'Lukas Podolski'",
    "jugador: 'Giroud'": "jugador: 'Olivier Giroud'",
    "jugador: 'Koscielny'": "jugador: 'Laurent Koscielny'",
    "jugador: 'Bendtner'": "jugador: 'Nicklas Bendtner'",
    "jugador: 'Mkhitaryan'": "jugador: 'Henrikh Mkhitaryan'",
    "jugador: 'Ozil'": "jugador: 'Mesut Özil'",
    "jugador: 'Alexis'": "jugador: 'Alexis Sánchez'",
    "jugador: 'Willian'": "jugador: 'Willian'",
    "jugador: 'Cole'": "jugador: 'Joe Cole'",
    "jugador: 'Terry'": "jugador: 'John Terry'",
    "jugador: 'Desailly'": "jugador: 'Marcel Desailly'",
    "jugador: 'Hasselbaink'": "jugador: 'Jimmy Floyd Hasselbaink'",
    "jugador: 'Zola'": "jugador: 'Gianfranco Zola'",
    "jugador: 'Morris'": "jugador: 'Jody Morris'",
    "jugador: 'Emerson'": "jugador: 'Emerson'",
    "jugador: 'Tiago'": "jugador: 'Tiago'",
    "jugador: 'Kezman'": "jugador: 'Mateja Kežman'",
    "jugador: 'Gudjohnsen'": "jugador: 'Eidur Gudjohnsen'",
    "jugador: 'Duff'": "jugador: 'Damien Duff'",
    "jugador: 'Shevchenko'": "jugador: 'Andriy Shevchenko'",
    "jugador: 'Robson-Kanu'": "jugador: 'Hal Robson-Kanu'",
    "jugador: 'Sturridge'": "jugador: 'Daniel Sturridge'",
    "jugador: 'Henderson'": "jugador: 'Jordan Henderson'",
    "jugador: 'Heskey'": "jugador: 'Emile Heskey'",
    "jugador: 'Bellamy'": "jugador: 'Craig Bellamy'",
    "jugador: 'Crouch'": "jugador: 'Peter Crouch'",
    "jugador: 'Fowler'": "jugador: 'Robbie Fowler'",
    "jugador: 'Keita'": "jugador: 'Naby Keita'",
    "jugador: 'Sead Kolasinac'": "jugador: 'Sead Kolašinac'",
    "jugador: 'Kolasinac'": "jugador: 'Sead Kolašinac'",
    "jugador: 'Vardy'": "jugador: 'Jamie Vardy'",
    "jugador: 'Albrighton'": "jugador: 'Marc Albrighton'",
    "jugador: 'Iheanacho'": "jugador: 'Kelechi Iheanacho'",
    "jugador: 'Maddison'": "jugador: 'James Maddison'",
    "jugador: 'Dewsbury-Hall'": "jugador: 'Kiernan Dewsbury-Hall'",
    "jugador: 'Tielemans'": "jugador: 'Youri Tielemans'",
    "jugador: 'Huth'": "jugador: 'Robert Huth'",
    "jugador: 'Ulloa'": "jugador: 'Leonardo Ulloa'",
    "jugador: 'Ricardo Pereira'": "jugador: 'Ricardo Pereira'",
    "jugador: 'Filho'": "jugador: 'Emerson Royal'",
    "jugador: 'Dávinson Sánchez'": "jugador: 'Dávinson Sánchez'",
    "jugador: 'Hojbjerg'": "jugador: 'Pierre-Emile Højbjerg'",
    "jugador: 'Richarlison'": "jugador: 'Richarlison'",
    "jugador: 'Antony'": "jugador: 'Antony'",
    "jugador: 'Van de Beek'": "jugador: 'Donny van de Beek'",
    "jugador: 'van de Beek'": "jugador: 'Donny van de Beek'",
    "jugador: 'Rodrygo'": "jugador: 'Rodrygo Goes'",
    "jugador: 'Joselu'": "jugador: 'Joselu'",
    "jugador: 'Brahim'": "jugador: 'Brahim Díaz'",
    "jugador: 'Bellingham'": "jugador: 'Jude Bellingham'",
    "jugador: 'Mbappe'": "jugador: 'Kylian Mbappé'",
    "jugador: 'Vinicius'": "jugador: 'Vinícius Jr'",
    "jugador: 'Gakpo'": "jugador: 'Cody Gakpo'",
    "jugador: 'Diaz'": "jugador: 'Luis Díaz'",
    "jugador: 'Robertson'": "jugador: 'Andrew Robertson'",
    "jugador: 'Firmino'": "jugador: 'Roberto Firmino'",
    "jugador: 'Mané'": "jugador: 'Sadio Mané'",
    "jugador: 'Alonso'": "jugador: 'Marcos Alonso'",
    "jugador: 'Gallagher'": "jugador: 'Conor Gallagher'",
    "jugador: 'Azpilicueta'": "jugador: 'César Azpilicueta'",
    "jugador: 'Rudiger'": "jugador: 'Antonio Rüdiger'",
    "jugador: 'March'": "jugador: 'Solly March'",
    "jugador: 'Cancelo'": "jugador: 'João Cancelo'",
    "jugador: 'Doku'": "jugador: 'Jérémy Doku'",
    "jugador: 'Minteh'": "jugador: 'Yankuba Minteh'",
    "jugador: 'Grealish'": "jugador: 'Jack Grealish'",
    "jugador: 'Maupay'": "jugador: 'Neal Maupay'",
    "jugador: 'Gross'": "jugador: 'Pascal Groß'",
    "jugador: 'Trossard'": "jugador: 'Leandro Trossard'",
    "jugador: 'Welbeck'": "jugador: 'Danny Welbeck'",
    "jugador: 'Mac Allister'": "jugador: 'Alexis Mac Allister'",
    "jugador: 'Ebiowei'": "jugador: 'Malcolm Ebiowei'",
    "jugador: 'Palmer'": "jugador: 'Cole Palmer'",
    "jugador: 'Botman'": "jugador: 'Sven Botman'",
    "jugador: 'Trippier'": "jugador: 'Kieran Trippier'",
    "jugador: 'Murphy'": "jugador: 'Jacob Murphy'",
    "jugador: 'Almiron'": "jugador: 'Miguel Almirón'",
    "jugador: 'Guimaraes'": "jugador: 'Bruno Guimarães'",
    "jugador: 'Barnes'": "jugador: 'Harvey Barnes'",
    "jugador: 'Isak'": "jugador: 'Alexander Isak'",
    "jugador: 'Cunha'": "jugador: 'Matheus Cunha'",
    "jugador: 'Hwang'": "jugador: 'Hwang Hee-chan'",
    "jugador: 'Bentancur'": "jugador: 'Rodrigo Bentancur'",
    "jugador: 'Romero'": "jugador: 'Cristian Romero'",
    "jugador: 'Kulusevski'": "jugador: 'Dejan Kulusevski'",
    "jugador: 'Son'": "jugador: 'Heung-min Son'",
    "jugador: 'Reijnders'": "jugador: 'Tijjani Reijnders'",
    "jugador: 'Weah'": "jugador: 'Timothy Weah'",
    "jugador: 'Cambiaso'": "jugador: 'Andrea Cambiaso'",
    "jugador: 'Kostic'": "jugador: 'Filip Kostić'",
    "jugador: 'Kamada'": "jugador: 'Daichi Kamada'",
    "jugador: 'Hofmann'": "jugador: 'Jonas Hofmann'",
    "jugador: 'Andrich'": "jugador: 'Robert Andrich'",
    "jugador: 'Goretzka'": "jugador: 'Leon Goretzka'",
    "jugador: 'Tella'": "jugador: 'Nathan Tella'",
    "jugador: 'Choupo-Moting'": "jugador: 'Eric Maxim Choupo-Moting'",
    "jugador: 'Coman'": "jugador: 'Kingsley Coman'",
    "jugador: 'Musiala'": "jugador: 'Jamal Musiala'",
    "jugador: 'Sane'": "jugador: 'Leroy Sané'",
    "jugador: 'Lewandowski'": "jugador: 'Robert Lewandowski'",
    "jugador: 'Müller'": "jugador: 'Thomas Müller'",
    "jugador: 'Kane'": "jugador: 'Harry Kane'",
    "jugador: 'Sané'": "jugador: 'Leroy Sané'",
    "jugador: 'Gnabry'": "jugador: 'Serge Gnabry'",
    "jugador: 'Kimmich'": "jugador: 'Joshua Kimmich'",
    "jugador: 'Davies'": "jugador: 'Alphonso Davies'",
    "jugador: 'Alaba'": "jugador: 'David Alaba'",
    "jugador: 'Robben'": "jugador: 'Arjen Robben'",
    "jugador: 'Ribéry'": "jugador: 'Franck Ribéry'",
    "jugador: 'Thiago'": "jugador: 'Thiago Alcántara'",
    "jugador: 'Haaland'": "jugador: 'Erling Haaland'",
    "jugador: 'Neymar'": "jugador: 'Neymar Jr'",
    "jugador: 'Messi'": "jugador: 'Lionel Messi'",
    "jugador: 'Ronaldo'": "jugador: 'Cristiano Ronaldo'",
}

with open('src/lib/golazosData.js', 'r', encoding='utf-8') as f:
    content = f.read()

original = content
count = 0

for old, new in replacements.items():
    occurrences = content.count(old)
    if occurrences > 0:
        content = content.replace(old, new)
        count += occurrences
        print(f"  {occurrences}x: {old.split(\"'\")[1]} → {new.split(\"'\")[1]}")

with open('src/lib/golazosData.js', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ TOTAL: {count} reemplazos realizados")
